services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auf67
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql

  mailpit:
    image: axllent/mailpit:v1.31
    ports:
      - "1025:1025"   # SMTP — сюда приложение отправляет письма
      - "8025:8025"   # веб-интерфейс — здесь письма читаем мы

volumes:
  auth-db-data:

